name: Deploy to EC2

on:
  push:
    branches:
      - master  # Déclenchement du workflow sur push vers la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.AWS_SECRET }}" > ssh_key
          chmod 600 ssh_key
- name: Create .ssh directory
        run: |
          mkdir -p ~/.ssh
      - name: Add SSH key to agent
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ssh_key

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh $EC2_USER@$EC2_HOST << 'EOF'
           
            git pull origin master
          
            
          EOF
